# Generated by Django 5.0.3 on 2024-04-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_tipo_cuenta_cuenta_tipo_cuenta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuenta'},
        ),
        migrations.AlterModelOptions(
            name='tipo_cuenta',
            options={'verbose_name': 'Tipo de cuenta', 'verbose_name_plural': 'Tipo de cuenta'},
        ),
    ]
