# Generated by Django 5.0.3 on 2024-04-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
